### PR TITLE
Bug fixes

### LINKED ISSUE #50: UnsupportedOperationException -> nth not supported on this type: PersistentArrayMap
I'm running 2d4485a.

```sh
> brew install clojure
> git clone git@github.com:FundingCircle/fc4c.git
> pushd fc4c/
> clojure -R:dev -e '(println "deps installed!")'
...
deps installed!
> git show --summary 
commit 2d4485a722a016390cf575b02c3b6fd1d8077be2 (HEAD -> master, origin/master, origin/HEAD)
Merge: 67f019c 86e4d8a
Author: Avi Flax <avi.flax@fundingcircle.com>
Date:   Tue Jul 3 11:03:42 2018 -0400

    Merge pull request #48 from FundingCircle/export-command
    
    New CLI command `export`
> ./wcb 
Now watching clipboard for Structurizr Express diagrams in YAML format. Hit ctrl-c to exit.
UnsupportedOperationException -> nth not supported on this type: PersistentArrayMap
```

The YAML doesn't get reformatted or cleansed as I was expecting.

```sh
> java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
> brew info clojure
clojure: stable 1.9.0.381
The Clojure Programming Language
https://clojure.org
/opt/boxen/homebrew/Cellar/clojure/1.9.0.381 (9 files, 20.9MB) *
  Built from source on 2018-07-04 at 15:15:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/clojure.rb
==> Dependencies
Required: rlwrap ✔
==> Requirements
Required: java >= 1.8 ✔
```

What am I missing?

### PR DESCRIPTION
**Pull request by aviflax**
Fixes #50 and another bug I found… please see commits.

### CODE REVIEW

**Comment by michaellennox** [comment]
Can confirm that with this branch I'm no longer experiencing the bug in #50. Thanks @aviflax

File: src/main/fc4c/integrations/structurizr/express/clipboard.clj [hunk 1]
```diff
@@ -13,7 +13,8 @@
 
 ;; Based on code found at https://gist.github.com/Folcon/1167903
 ;; This was a simple var at one point but that broke CI builds, which run on
-;; headless machines; therefore this needs to be a function.
+;; headless machines; therefore this needs to be a function and it shouldn’t be
```
Comment (sgerrand) [inline src/main/fc4c/integrations/structurizr/express/clipboard.clj]: 📝 You _can_ run builds using `Xvfb` or something similar if you'd like to test the UI functionality.

File: test/fc4c/integrations/structurizr/express/clipboard_test.clj [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+  (:import [java.awt.datatransfer StringSelection]))
+
+(defn- faux-spit
+  "Used as a replacement for c/spit because when running tests in our CI
+  environment there’s no clipboard available and c/spit just raises an exception
+  to that effect.
+
+  It’d probably be better to install X11 or Xorg and run them headless so that a
+  clipboard would be available and we could test with the actual function, but I
+  don’t have time to figure that out right now."
```
Comment (sgerrand) [inline test/fc4c/integrations/structurizr/express/clipboard_test.clj]: 💡 Ah, you're on the same page.
